name: deaf_captioning_app
description: "AI-based real-time multilingual captioning app for Deaf users with speech-to-text, text simplification, and pictogram integration"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI and State Management
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  get: ^4.6.6
  
  # Speech Recognition & Audio
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1
  # flutter_tts: ^3.8.5  # Temporarily disabled for Windows build
  audioplayers: ^5.2.1
  
  # Networking & WebSockets
  http: ^1.1.2
  web_socket_channel: ^2.4.0
  dio: ^5.4.0
  
  # Local Storage & Database
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # ML & AI Integration (removed non-existent packages)
  # tflite_flutter: ^0.10.4
  # onnxruntime: ^1.16.3
  
  # Language Processing
  translator: ^1.0.0
  
  # UI Enhancement
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  shimmer: ^3.0.0
  
  # Accessibility (removed non-existent package)
  
  # Utils
  path_provider: ^2.1.1
  url_launcher: ^6.2.2
  package_info_plus: ^4.2.0
  connectivity_plus: ^5.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/models/
    - assets/audio/
    - assets/dictionaries/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/captoniner_logo.png"
  min_sdk_android: 21 # Android 5.0
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/captoniner_logo.png"
  
